export interface Students {
    id: string,
    fname: string,
    fnameE: string,
    SnameE: string,
    Sname: string,
    TnameE: string,
    Tname: string,
    Lname: string,
    LnameE: string,
    parantEmail: string,
    class:string,
    lSchool:string,
    PlacePD: number,
    grade:number,
    ContryNum: string,
    PirthDate:number,
    six: string,
    country:string,
    section:string,
    city:string,
    image:string,
    phone:number,
    isActive:boolean
}